### ISSUE TITLE
Segfault when using difference()

### ISSUE THREAD

**Issue by nomike** [pythonscad/pythonscad#10]
**Describe the bug**
When rendering this code, PythonSCAD segfaults:

```python
from openscad import *

obj = difference([cube(20), cube(10)])
show(obj)```
```

I know the code is not correct, but PythonSCAD should not segfault because of this.

I've also reported this with the OpenSCAD project as <https://github.com/openscad/openscad/issues/5906> but I guess this should be handled upstream.

**Environment and Version info (please complete the following information):**
AppImage

**Comment by gsohler** [comment]
Thank you for filing the issue here.
When manifold is upstream to openscad, suppose here is downstream :)

I have tested your example here and i could not find the crash. suppose we best compare versions next.
OTOH i have fixed a nasty double free error yesterday, so my maybe this resolved it. its checked in.
please let me know how you want to proceed
|
![Image](https://github.com/user-attachments/assets/d8a3058d-ac85-4c8b-9521-b0eb2f22dee7)

**Comment by nomike** [comment]
I could reproduce this with https://www.pythonscad.org/downloads/PythonSCAD-2025-04-02.AppImage.
I'm currently trying to package PythonSCAD for GNU guix but I'm still having some issues there. I probably will open an issue for that as well if I'm not able to figure that out soon.

Once I have it up and running, I can try if I still experience the issue.

**Comment by nomike** [comment]
But yes, a double free sounds like a good candidate.

**Comment by gsohler** [comment]
Yes, i can replicate the crash in the AppImage, but in the latest version its gone.
Suppose we need an updated AppImage

**Comment by nomike** [comment]
I just managed to build pythonscad with commit 39eb62366ef0f49a71d2d6e63441424e75c74690 and the issue is gone.

I guess this should be reported with openscad, as they have to fix it on their end as well.

**Comment by gsohler** [comment]
Yes of course,

But dont have any idea, which change has actually resolved the crash. So i cannot create a PR within 5 minutes.
There are quite some PR's already pending, which offer bugfixes and additional features to upstream.
Honestly I dont want to stress these guys with yet another one. In any case they focus on the venv as 1st priority in any case.

BTW: new AppImage is online

**Comment by nomike** [comment]
Which commit was the previous appimage based on? I can try to figure out which commit introduced the fix.

**Comment by gsohler** [comment]
the commit is 853bfcfbe14b4d954c4385e24a90b8bfc55501e8

its likely the recent bugfix wit the double-free , but i cant be sure

**Comment by nomike** [comment]
I'm building that commit right now.
I can confirm, that it does not exit in 54bbcb5, because I have built that already.

If it's happening in 853bfcf, there are 89 commits in between which could be the culprit.
If I do a binary search I'm guaranteed to find the respective commit with 7 or less builds.

But I can probably weed out some of the commits already which should narrow things down significantly.

**Comment by nomike** [comment]
https://github.com/pythonscad/pythonscad/commit/853bfcfbe14b4d954c4385e24a90b8bfc55501e8 is having the bug.

**Comment by nomike** [comment]
The big was fixed in 618b8179c31ae6e5d6134507b22a9d556eb0aa21.

I will report this to the OpenSCAD project.

**Comment by gsohler** [comment]
very likely it's the very last diff, but you could user your "binary search
algorithm"  on this file only

**Comment by nomike** [comment]
In OpenSCAD this bug no longer exists as well. Seems like the pulled it from pythonscad.
So this ticket is no longer relevant.
